name: qsuite_env
channels:
  - conda-forge
dependencies:
  - numpy>=1.17
  - paramiko>=2.7.2
  - pathos>=0.2.7
  - tabulate>=0.8.7
  - python-dotenv>=1.0.0
  - pathlib>=1.0.1
  - pip
  - pip:
      - -e .
